name: ci-sonarcloud

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  run-ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
